# Generic
spring.application.name=rabbitmq-cron
spring.task.scheduling.pool.size=5

# Exchanges
spring.rabbitmq.exchange.scheduler=scheduler

# Routing Keys
spring.rabbitmq.routing.key.second-tick=second
spring.rabbitmq.routing.key.minute-tick=minute
spring.rabbitmq.routing.key.hour-quarter-tick=hour-quarter
spring.rabbitmq.routing.key.hour-tick=hour
